with bonuses 11.04
Sasha-nagibator/python pull request #1
Opened 2021-04-11 15:51 UTC by Sasha-nagibator

2021-04-19 15:40 UTC, corwinnn requested changes

2021-04-19 15:40 UTC, corwinnn commented on README.md
> +__Инструкция по запуску__
в ридми отсутствует маркдаун, читать сложно

2021-04-19 15:40 UTC, corwinnn commented on ceasar.py
> +class Cezar():
кажется, по-английски пишется не так, но не критично, можно оставить

2021-04-19 15:40 UTC, corwinnn commented on ceasar.py
> +        self.text = "abcde ABCDE"
для чего это?

2021-04-19 15:40 UTC, corwinnn commented on ceasar.py
> +        return self.encrypt_decrypt(text, key_expected, "d")
почему d?

2021-04-19 15:40 UTC, corwinnn commented on hill.py
> +                return np.array(np.round(inv(key) * d) * int(invert(d, 26)), dtype=int) % 26
магическая константа

2021-04-19 15:40 UTC, corwinnn commented on review.py
> +    f = open(sys.argv[1], "r")
почему не with open?

2021-04-19 15:40 UTC, corwinnn commented on review.py
> +        a = Cezar()
однобуквенная переменная

2021-04-19 15:40 UTC, corwinnn commented on vernam.py
> +            res = (code_char ^ key_char)          # '^' is XOR
для чего скобки?

2021-04-20 17:16 UTC, ab8080 commented on ceasar.py
> +        self.text = "abcde ABCDE"
Забыл убрать, в начале так тестировал

2021-04-20 17:21 UTC, ab8080 commented on ceasar.py
> +        return self.encrypt_decrypt(text, key_expected, "d")
У функции encrypt_decrypt последний параметр - это действие ("d" - decrypt или "e" - encrypt). Тут я подобрал предпологаемый ключ и с помощью него расшифровываю

2021-04-20 17:34 UTC, ab8080 commented on vernam.py
> +            res = (code_char ^ key_char)          # '^' is XOR
забыл убрать

2021-04-21 09:32 UTC, corwinnn requested changes
У функций и классов отсутствует документация, напиши ее

2021-04-21 09:32 UTC, corwinnn commented on README.md
> +   python3 review.py /home/aleksandr/Review/python/1.txt ceasar encrypt
напиши комментарии к примерам и сделай, чтобы примеры запускались у всех
не у всех в home есть папка aleksandr

2021-04-21 09:32 UTC, corwinnn commented on ceasar.py
> +        return self.encrypt_decrypt(text, key_expected, "d")
когда читаешь непонятно, передавай действие словом или сделай переменную глобальную DECRYPT = "d"

2021-04-21 09:32 UTC, corwinnn commented on ceasar.py
> +        for i in range(len(text)):
для чего индекс? итерируйся по символам

2021-04-21 09:32 UTC, corwinnn commented on ceasar.py
> +        if ord(stats[max_count]) < 91:
магическая константа

2021-04-21 09:32 UTC, corwinnn commented on hill.py
> +import numpy as np
неправильный порядок импортов

2021-04-21 09:32 UTC, corwinnn commented on hill.py
> +            matr.append([0] * len(text))
можно ли в одну строчку?

2021-04-21 09:32 UTC, corwinnn commented on hill.py
> +            txt.append([ord(text[i]) - ord('A')])
можно ли в одну строку? и итерируйся по символам

2021-04-21 09:32 UTC, corwinnn commented on review.py
> +                code.decrypt(encrypted_img, output_txt, number_of_symbols)
сделай чтобы аргументы передавались как именованные аргументы командной строки 
например с помощью библиотеки argparse

2021-04-21 09:32 UTC, corwinnn commented on vernam.py
> +        result = ""
сделай кавычки все либо двойные либо одинарные

2021-04-22 17:09 UTC, ab8080 commented on hill.py
> +            matr.append([0] * len(text))
![image](https://user-images.githubusercontent.com/79227642/115755953-94b94300-a3a6-11eb-997b-91ad5b2eeb09.png)
так нельзя

2021-04-22 17:10 UTC, ab8080 commented on hill.py
> +            matr.append([0] * len(text))
сразу везде меняется

2021-04-22 19:53 UTC, corwinnn requested changes

2021-04-22 19:53 UTC, corwinnn commented on hill.py
> +            matr.append([0] * len(text))
значит надо через for

2021-04-22 19:53 UTC, corwinnn commented on README.md
> +```
разве не надо теперь с аргпарс передавать аргументы через -- ?

2021-04-22 19:53 UTC, corwinnn commented on ceasar.py
> +        from collections import Counter
почему не вверху?

2021-04-22 19:53 UTC, corwinnn commented on hill.py
> +                d = int(det(key))
однобуквенная переменная

2021-04-22 19:53 UTC, corwinnn commented on review.py
> +            code.decrypt(args.input_img, args.txt_file, int(args.output_img_or_chars_num))
много ифов
сделай словарь из функций и потом вызови нужную по ключу

2021-04-22 19:53 UTC, corwinnn commented on stegonography.py
> +        if text_len >= img_len / 8 - self.BMP_HEADER_SIZE:
магическая константа

2021-04-22 19:53 UTC, corwinnn commented on vernam.py
> +        result = ""
не исправлено

2021-04-25 10:20 UTC, ab8080 commented on README.md
> +```
У меня без -- работает

2021-04-26 18:13 UTC, corwinnn requested changes

2021-04-26 18:13 UTC, corwinnn commented on stegonography.py
> +        return text_mask, img_mask
убери магические константы тут

2021-04-26 18:13 UTC, corwinnn commented on vigenere.py
> +                    result += chr((ord(char1) + ord(char2) - 2 * ord("a")) % self.length + ord("a"))
почему * 2?

2021-04-26 21:25 UTC, ab8080 commented on vigenere.py
> +                    result += chr((ord(char1) + ord(char2) - 2 * ord("a")) % self.length + ord("a"))
ord(char1) - ord("a") это то на каком расстоянии от начала алфавита находится буква из текста, 
ord(char2) - ord("a") это то на каком расстоянии от начала алфавита находится буква из ключа.
В шифре Виженера каждая буква зашифрованного сообщения находится на расстоянии 
(ord(char1) - ord("a")) + (ord(char2) - ord("a")) от начала алфавита (по модулю длины алфавита)

2021-05-05 20:27 UTC, corwinnn requested changes

2021-05-05 20:27 UTC, corwinnn commented on ceasar.py
> +    def hack(self, text, _, __):
что за подчеркивания?

2021-05-05 20:27 UTC, corwinnn commented on stegonography.py
> +        output_image = open(output_img_name, "wb")
with open

2021-05-05 20:27 UTC, corwinnn commented on stegonography.py
> +        output_image = open(output_img_name, "wb")
здесь и далее

2021-05-05 20:27 UTC, corwinnn commented on review.py
> +from stegonography import Stegonography
почини порядок импортов во всех файлах

2021-05-05 20:27 UTC, corwinnn commented on review.py
> +    if args.chiper != "steg":
напиши комментарии, непонятна логика

2023-02-04 17:16 UTC, merged